const characters = [
    {
        colorClass: 'lil',
        name: 'Lilthet Suncatcher',
        nameDesc: 'Lilthet Suncatcher (she probably had many nicknames but usually only family members or close friends know them, maybe eventually the party members)',
        raceAndClass: "Centaur; Cleric, lots of spells and being kinda bulky for a spellcaster it's kinda fun.",
        background: 'She comes from a relatively small traveling band of centaurs full of merchants and some warriors to protect them. Huge family and knows quite a lot of random customs from different lands because of the travels. Known in her village as basically their chosen one and had a lot of pressure to live up to that image. This is because the god Heliod blessed/choose her at birth. She is now in this quest as basically a coming of age ceremony to show her who she is supposed to be and who she will become.',
        alignment: 'Lawful Good; she strives to always do the right thing and shys away from unnecessary death. Loves to try to bring people together and wants to bring Sunshine to everyone she can!',
        dietyOrPatron: "Heliod; she technically didn't choose him, he choose her, but she believes in all that he stands for but thinks he can be pretty arrogant at times and can understand why others do not like him.",
        personality: "Loyal to a fault, easy to trust but not stupid she won't let others get away with everything. Very emotionally driven.",
        motivation: 'She is on her Coming of Age Journey to seek who she will become and to live up to her tribes expectations that she will be a renowned champion of Heliod.',
        appearance: 'A really tall Clydesdale Centaur with a pale sandy colored coat. A long blonde braid for her hair and tail. Enjoys wearing light blues and yellows in her clothing. Many bags and packs since she cann carry so much. A large staff with Heliod symbols, other Heliod symbols on her necklace and clothing as well as wearing a laurel around her head.',
        funFact: 'She feels super pressured almost constantly to keep people together and ensure success. Also weird Nyxborn stuff like her hair and eyes sometimes have a glow and her hair can sometimes float, as well as having birds chirp when she laughs.',
        oneLiner: '"Okay, how about we all take a seat and calm down to talk about this? I have the special talking stick!"',
        image: 'images/lilthet.jpg',
        imgAlt: 'Centaur Cleric',
    }, 
    {
        colorClass: 'cer',
        name: 'Cerein Serudath',
        nameDesc: 'Cerein Serudath, previously Princess Cordelia Serudath ',
        raceAndClass: 'Triton, Phantom Rouge. Darling is a literal agent of death.',
        background: 'Born as the Princess of Saphiren and the younger twin of her brother Faros. She grew up causing chaos along with her brother <em>and a certain someone,</em> until eventually her schemes became too dangerous. At 10 years old, she witnessed her brother die, narrowly escaping death herself, and left the kingdom behind due to the immense grief. More chaos. More death. At 15, her and her parents were killed (Consequences for your actions? What?). She was then chosen by Erebos to become his Nyxborn champion.',
        alignment: 'Lawful Evil, now that I think about it.',
        dietyOrPatron: 'The one and only, Erebos.',
        personality: 'She cares for <em>almost</em> no one except herself, her family, and her kingdom. She is all too eager to kill but will always respect the dead. She keeps to herself and does everything she can to carry out the will of Erebos and seek his approval.',
        motivation: "Her entire purpose in this second life is to obey Erebos' command and bring down his foes. However, she still has a soft spot for her home and family.",
        appearance: "5'1'' Baby blue triton with large elegant fins that now fade to black. Her pitch black eyes sheen silver as they reflect nothing but darkness and death. She wears black clothes trimmed with silver and several belts, small chains, and small bags to carry several small items. She wears an inky black cloak that seems to blend into the shadows except for the symbol of Erebos on the right shoulder. She carries several weapons which are now often hidden by the cloak",
        funFact: 'Due to being a Nyxborn: One can often see haunting black mist trailing behind her blades and other weapons as she uses them. Her scales give off a silver sheen under moonlight. *If* she screams or yells, the voices of long-gone souls seem to echo out and accompany her. And, when she laughs, all who can hear suddenly feel cold as a foreboding chill crawls up their spine.',
        oneLiner: '"See you in the Underworld."',
        image: 'images/cerein.jpg',
        imgAlt: 'Triton Rouge',
    },
    // Template
    // {
    //     colorClass: '',
    //     name: '',
    //     nameDesc: '',
    //     raceAndClass: '',
    //     background: '',
    //     alignment: '',
    //     dietyOrPatron: '',
    //     personality: '',
    //     motivation: '',
    //     appearance: '',
    //     funFact: '',
    //     oneLiner: '',
    //     image: '',
    //     imgAlt: '',
    // },
]

export default characters